export function buildAdminStyles(): string {
	return [
		'*, *::before, *::after { box-sizing: border-box; }',
		'body { font-family: system-ui, sans-serif; margin: 0; padding: 20px 24px; background: #f4f5f7; color: #1a1a1a; }',
		'h1 { margin: 0 0 4px; font-size: 1.4rem; }',
		'.subtitle { color: #555; margin: 0 0 20px; font-size: 0.9rem; }',
		'.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 12px; margin-bottom: 18px; }',
		'.stat-card { background: #fff; border: 1px solid #ddd; border-left: 5px solid #ccc; border-radius: 8px; padding: 12px 14px; }',
		'.stat-label { font-size: 0.72rem; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; color: #666; }',
		'.stat-value { margin-top: 6px; font-size: 1.45rem; font-weight: 700; color: #111827; }',
		'.admin-page-tabs { display: flex; gap: 10px; flex-wrap: wrap; margin: 0 0 18px; }',
		'.admin-page-tab { border: 1px solid #cfd6de; border-radius: 999px; background: #fff; color: #334155; cursor: pointer; padding: 10px 16px; font-size: 0.9rem; font-weight: 700; }',
		'.admin-page-tab.is-active { background: #0f172a; border-color: #0f172a; color: #fff; box-shadow: 0 10px 24px rgba(15, 23, 42, 0.16); }',
		'.admin-page-panel { display: none; }',
		'.admin-page-panel.is-active { display: block; }',
		'.filter-bar { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 22px; padding: 14px 16px; background: #fff; border-radius: 8px; border: 1px solid #ddd; }',
		'.filter-bar label { font-size: 0.9rem; color: #333; }',
		'.filter-bar input, .filter-bar select { margin-left: 6px; padding: 6px 8px; border: 1px solid #ccc; border-radius: 4px; }',
		'.filter-bar button { padding: 6px 10px; border: 1px solid #bbb; border-radius: 5px; background: #f0f0f0; cursor: pointer; font-size: 0.85rem; }',
		'.filter-bar button:hover { background: #e0e0e0; }',
		'.admin-panel { background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: 14px; margin-bottom: 22px; }',
		'.admin-panel h2 { margin: 0 0 8px; font-size: 1rem; }',
		'.admin-panel p { margin: 8px 0; font-size: 0.88rem; color: #444; }',
		'.toggle-row { display: flex; align-items: center; gap: 10px; font-weight: 600; margin-top: 10px; flex-wrap: wrap; }',
		'.toggle-row select { min-width: 220px; padding: 8px 10px; border: 1px solid #c7ccd1; border-radius: 6px; font-size: 0.9rem; background: #fff; }',
		'.toggle-help { margin-top: 8px; color: #555; }',
		'.auto-post-status { margin-top: 10px; font-size: 0.83rem; color: #333; }',
		'.auto-post-status.ok { color: #1a7f37; }',
		'.auto-post-status.err { color: #b30000; }',
		'.token-exchange { background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: 14px; margin-bottom: 22px; }',
		'.token-exchange label { display: block; margin-top: 10px; font-size: 0.9rem; color: #334155; }',
		'.token-exchange input { width: 100%; max-width: 480px; margin-top: 6px; padding: 9px 10px; border: 1px solid #cbd5e1; border-radius: 6px; }',
		'.token-exchange button { margin-top: 12px; margin-right: 8px; padding: 9px 14px; border-radius: 8px; border: 1px solid #cbd5e1; background: #fff; cursor: pointer; font-weight: 700; }',
		'.token-exchange button:hover { background: #f8fafc; }',
		'.facebook-post-hub { background: linear-gradient(180deg, #ffffff, #f8fafc); border: 1px solid #d8e0ea; border-radius: 16px; padding: 20px; box-shadow: 0 18px 32px rgba(15, 23, 42, 0.06); }',
		'.facebook-post-head { display: flex; justify-content: space-between; gap: 14px; align-items: flex-start; flex-wrap: wrap; margin-bottom: 16px; }',
		'.facebook-post-head h2 { margin: 0 0 4px; font-size: 1.15rem; }',
		'.facebook-post-head p { margin: 0; color: #526277; line-height: 1.55; }',
		'.facebook-post-list { display: grid; gap: 14px; }',
		'.fb-rank-card { background: #fff; border: 1px solid #d7dde5; border-radius: 16px; padding: 18px; box-shadow: 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.fb-rank-post_now { box-shadow: inset 4px 0 0 #047857, 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.fb-rank-fallback_pick { box-shadow: inset 4px 0 0 #2563eb, 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.fb-rank-manual_review { box-shadow: inset 4px 0 0 #d97706, 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.fb-rank-unlikely { box-shadow: inset 4px 0 0 #94a3b8, 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.fb-rank-head { display: flex; justify-content: space-between; gap: 12px; align-items: flex-start; }',
		'.fb-rank-topline { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; margin-bottom: 10px; }',
		'.fb-rank-pill { display: inline-flex; align-items: center; padding: 6px 10px; border-radius: 999px; font-size: 0.78rem; font-weight: 800; letter-spacing: 0.03em; text-transform: uppercase; }',
		'.fb-rank-pill.is-post-now { background: #dcfce7; color: #166534; }',
		'.fb-rank-pill.is-fallback { background: #dbeafe; color: #1d4ed8; }',
		'.fb-rank-pill.is-review { background: #ffedd5; color: #c2410c; }',
		'.fb-rank-pill.is-unlikely { background: #e2e8f0; color: #475569; }',
		'.fb-rank-score { font-size: 0.8rem; color: #64748b; font-weight: 700; }',
		'.fb-rank-card h3 { margin: 0 0 4px; font-size: 1.05rem; }',
		'.fb-rank-area { margin: 0; color: #0f172a; font-weight: 600; }',
		'.fb-rank-headline { margin: 8px 0 0; color: #64748b; line-height: 1.5; }',
		'.fb-rank-reason { margin: 14px 0 0; color: #1f2937; line-height: 1.6; }',
		'.fb-rank-tags { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }',
		'.fb-rank-tag { display: inline-flex; align-items: center; padding: 6px 10px; border-radius: 999px; background: #f8fafc; border: 1px solid #e2e8f0; color: #334155; font-size: 0.8rem; }',
		'.fb-rank-actions { margin-top: 14px; }',
		'.forecast-hub { background: linear-gradient(180deg, #ffffff, #f8fafc); border: 1px solid #d8e0ea; border-radius: 16px; padding: 20px; box-shadow: 0 18px 32px rgba(15, 23, 42, 0.06); }',
		'.forecast-hub-head { display: flex; justify-content: space-between; gap: 14px; align-items: flex-start; flex-wrap: wrap; margin-bottom: 16px; }',
		'.forecast-hub-head h2 { margin: 0 0 4px; font-size: 1.15rem; }',
		'.forecast-hub-head p { margin: 0; color: #526277; }',
		'.forecast-refresh { padding: 10px 16px; border: none; border-radius: 10px; background: #1d4ed8; color: #fff; font-weight: 700; cursor: pointer; box-shadow: 0 10px 18px rgba(29, 78, 216, 0.2); }',
		'.forecast-refresh:hover { background: #1e40af; }',
		'.forecast-subtabs { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 18px; }',
		'.forecast-loc-tab { min-width: 160px; display: flex; flex-direction: column; gap: 4px; align-items: flex-start; padding: 12px 16px; border-radius: 14px; border: 1px solid #d5dce5; background: #fff; cursor: pointer; box-shadow: 0 8px 18px rgba(15, 23, 42, 0.06); }',
		'.forecast-loc-tab.is-active { border-color: #f97316; box-shadow: 0 10px 20px rgba(249, 115, 22, 0.18); transform: translateY(-1px); }',
		'.forecast-loc-label { font-weight: 700; color: #0f172a; }',
		'.forecast-loc-region { font-size: 0.8rem; color: #64748b; }',
		'.discussion-tab-count { font-size: 0.8rem; color: #475569; }',
		'.forecast-status { min-height: 22px; margin-bottom: 14px; font-size: 0.86rem; color: #475569; }',
		'.forecast-status.err { color: #b42318; }',
		'.forecast-view { display: none; }',
		'.forecast-view.is-active { display: block; }',
		'.forecast-city-shell { background: #fff; border-radius: 16px; border: 1px solid #d7dde5; padding: 18px; }',
		'.forecast-city-head { display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; flex-wrap: wrap; margin-bottom: 14px; }',
		'.forecast-city-head h3 { margin: 0; font-size: 1.05rem; }',
		'.forecast-city-head p { margin: 4px 0 0; color: #64748b; font-size: 0.88rem; }',
		'.forecast-updated { font-size: 0.84rem; color: #64748b; }',
		'.forecast-periods { display: grid; gap: 12px; }',
		'.forecast-period-card { display: grid; grid-template-columns: 1fr auto; gap: 16px; align-items: start; padding: 16px 18px; border-radius: 16px; border: 1px solid #dde4ec; background: #fff; box-shadow: inset 4px 0 0 #f59e0b, 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.forecast-period-card.is-night { box-shadow: inset 4px 0 0 #4f46e5, 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.forecast-period-card h4 { margin: 0 0 4px; font-size: 1rem; }',
		'.forecast-period-card .forecast-short { margin: 0 0 10px; color: #64748b; font-size: 0.9rem; }',
		'.forecast-period-card .forecast-detail { margin: 0; color: #1f2937; line-height: 1.55; }',
		'.forecast-period-side { min-width: 132px; text-align: right; }',
		'.forecast-period-temp { font-size: 2rem; font-weight: 800; color: #ea580c; line-height: 1; }',
		'.forecast-period-card.is-night .forecast-period-temp { color: #16a34a; }',
		'.forecast-period-meta { margin-top: 8px; font-size: 0.85rem; color: #64748b; line-height: 1.5; }',
		'.forecast-summary-card { background: #fff; border: 1px solid #d7dde5; border-radius: 16px; padding: 18px; }',
		'.forecast-summary-head { display: flex; justify-content: space-between; gap: 10px; align-items: center; flex-wrap: wrap; margin-bottom: 12px; }',
		'.forecast-summary-head h3 { margin: 0; font-size: 1.05rem; }',
		'.forecast-summary-actions { display: flex; gap: 8px; flex-wrap: wrap; }',
		'.forecast-summary-actions button { padding: 9px 14px; border-radius: 10px; border: 1px solid #cbd5e1; background: #fff; cursor: pointer; font-weight: 700; }',
		'.forecast-summary-actions .primary { background: #2563eb; border-color: #2563eb; color: #fff; }',
		'.forecast-summary-actions .accent { background: #f97316; border-color: #f97316; color: #fff; }',
		'.forecast-summary-actions button:hover { filter: brightness(0.97); }',
		'.forecast-summary-editor { width: 100%; min-height: 360px; border-radius: 14px; border: 1px solid #d8e0ea; background: #f8fafc; padding: 16px; font: 0.92rem/1.6 Consolas, Monaco, monospace; color: #0f172a; resize: vertical; }',
		'.forecast-summary-meta { margin-top: 8px; font-size: 0.84rem; color: #64748b; }',
		'.discussion-hub { background: linear-gradient(180deg, #ffffff, #f8fafc); border: 1px solid #d8e0ea; border-radius: 16px; padding: 20px; box-shadow: 0 18px 32px rgba(15, 23, 42, 0.06); }',
		'.discussion-list { display: grid; gap: 10px; }',
		'.discussion-card { background: #fff; border: 1px solid #d7dde5; border-radius: 16px; overflow: hidden; box-shadow: 0 8px 18px rgba(15, 23, 42, 0.05); }',
		'.discussion-card summary { list-style: none; cursor: pointer; padding: 16px 18px; display: flex; justify-content: space-between; gap: 12px; align-items: flex-start; }',
		'.discussion-card summary::-webkit-details-marker { display: none; }',
		'.discussion-card summary:hover { background: #f8fafc; }',
		'.discussion-title { font-size: 1rem; font-weight: 700; color: #0f172a; }',
		'.discussion-issued { margin-top: 6px; font-size: 0.84rem; color: #64748b; }',
		'.discussion-toggle { font-size: 0.85rem; color: #64748b; white-space: nowrap; }',
		'.discussion-body-wrap { border-top: 1px solid #e8edf3; padding: 14px 18px 18px; }',
		'.discussion-body { margin: 0; padding: 14px; background: #f8fafc; border: 1px solid #dde4ec; border-radius: 14px; font: 0.86rem/1.65 Consolas, Monaco, monospace; color: #111827; white-space: pre-wrap; max-height: 420px; overflow: auto; }',
		'.discussion-actions { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 12px; }',
		'.discussion-actions button, .discussion-actions a { padding: 9px 14px; border-radius: 10px; border: 1px solid #cbd5e1; background: #fff; color: #0f172a; cursor: pointer; font-weight: 700; text-decoration: none; }',
		'.discussion-actions .primary { background: #2563eb; border-color: #2563eb; color: #fff; }',
		'.discussion-empty { background: #fff; border: 1px solid #d7dde5; border-radius: 16px; padding: 18px; color: #64748b; }',
		'.outlook-summary { margin: 0 0 16px; padding: 14px 16px; background: linear-gradient(180deg, #fff7ed, #fffbeb); border: 1px solid #fed7aa; border-radius: 14px; color: #9a3412; font-weight: 600; line-height: 1.5; }',
		'.outlook-image-card { margin-bottom: 16px; }',
		'.outlook-image-link { display: block; border-radius: 16px; overflow: hidden; border: 1px solid #d8e0ea; background: #fff; box-shadow: 0 12px 24px rgba(15, 23, 42, 0.06); }',
		'.outlook-image { display: block; width: 100%; height: auto; background: #fff; }',
		'.outlook-empty { background: #fff; border: 1px solid #d7dde5; border-radius: 16px; padding: 18px; color: #64748b; }',
		'.token-exchange { background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: 14px; margin-bottom: 22px; }',
		'.token-exchange h2 { margin: 0 0 8px; font-size: 1rem; }',
		'.token-exchange label { display: block; margin: 8px 0; font-size: 0.87rem; }',
		'.token-exchange input { padding: 6px 8px; border: 1px solid #ccc; border-radius: 4px; font-size: 0.9rem; }',
		'.token-exchange button { margin-top: 8px; padding: 7px 14px; font-size: 0.85rem; }',
		'.alerts-list { display: flex; flex-direction: column; gap: 14px; }',
		'.alert-card { background: #fff; border-radius: 8px; border: 1px solid #ddd; border-left: 5px solid #ccc; overflow: hidden; }',
		'.alert-card.sev-severe   { border-left-color: #cc0000; }',
		'.alert-card.sev-extreme  { border-left-color: #7b0000; }',
		'.alert-card.sev-moderate { border-left-color: #e07000; }',
		'.alert-card.sev-minor    { border-left-color: #b8a000; }',
		'.card-header { display: flex; justify-content: space-between; align-items: flex-start; padding: 12px 16px 10px; gap: 12px; flex-wrap: wrap; }',
		'.card-title { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; font-size: 0.95rem; }',
		'.badge { color: #fff; font-size: 0.72rem; font-weight: 700; padding: 2px 7px; border-radius: 3px; letter-spacing: 0.04em; }',
		'.area { color: #555; font-size: 0.88rem; }',
		'.card-meta { display: flex; gap: 16px; font-size: 0.82rem; color: #666; white-space: nowrap; }',
		'.card-details { border-top: 1px solid #eee; }',
		'.card-details summary { padding: 8px 16px; cursor: pointer; font-size: 0.85rem; color: #0066cc; user-select: none; }',
		'.card-details summary:hover { background: #f7f7f7; }',
		'.details-grid { display: grid; grid-template-columns: 260px 1fr; gap: 0; padding: 12px 16px 14px; border-top: 1px solid #f0f0f0; }',
		'.detail-col { padding: 0 12px; }',
		'.detail-col:first-child { border-right: 1px solid #eee; padding-left: 0; }',
		'.detail-col p { margin: 4px 0; font-size: 0.85rem; }',
		'.post-preview { font-family: system-ui, sans-serif; font-size: 0.84rem; line-height: 1.65; white-space: pre-wrap; word-break: break-word; background: #f8f9fa; border: 1px solid #e0e0e0; border-radius: 5px; padding: 10px 12px; margin: 4px 0 0; }',
		'.card-actions { padding: 10px 16px; border-top: 1px solid #eee; background: #fafafa; }',
		'.btn-preview { padding: 7px 16px; background: #1877f2; color: #fff; border: none; border-radius: 5px; cursor: pointer; font-size: 0.88rem; font-weight: 600; }',
		'.btn-preview:hover { background: #1565d8; }',
		'.modal-overlay { display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.5); z-index: 100; align-items: center; justify-content: center; }',
		'.modal-overlay.open { display: flex; }',
		'.modal { background: #fff; border-radius: 10px; width: 640px; max-width: 96vw; max-height: 90vh; display: flex; flex-direction: column; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,0.22); }',
		'.modal-header { padding: 14px 18px; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; align-items: center; }',
		'.modal-header h2 { margin: 0; font-size: 1rem; }',
		'.modal-close { background: none; border: none; font-size: 1.4rem; cursor: pointer; color: #555; padding: 0 4px; line-height: 1; }',
		'.modal-body { padding: 16px 18px; overflow-y: auto; flex: 1; }',
		'.modal-body label { display: block; font-size: 0.82rem; font-weight: 600; color: #444; margin-bottom: 6px; }',
		'.modal-body textarea { width: 100%; height: 380px; font-family: system-ui, sans-serif; font-size: 0.88rem; line-height: 1.65; padding: 10px; border: 1px solid #ccc; border-radius: 6px; resize: vertical; }',
		'.char-count { font-size: 0.78rem; color: #888; margin-top: 4px; text-align: right; }',
		'.modal-footer { padding: 12px 18px; border-top: 1px solid #eee; display: flex; gap: 10px; justify-content: flex-end; align-items: center; flex-wrap: wrap; }',
		'.btn-cancel { padding: 7px 16px; background: #f0f0f0; border: 1px solid #bbb; border-radius: 5px; cursor: pointer; font-size: 0.88rem; }',
		'.btn-post { padding: 7px 18px; background: #1877f2; color: #fff; border: none; border-radius: 5px; cursor: pointer; font-size: 0.88rem; font-weight: 600; }',
		'.btn-post:hover { background: #1565d8; }',
		'.btn-post:disabled { background: #94b8f5; cursor: not-allowed; }',
		'.post-status { font-size: 0.84rem; padding: 6px 10px; border-radius: 4px; display: none; flex: 1; min-width: 0; }',
		'.post-status.ok  { background: #e6f4ea; color: #1a7f37; display: block; }',
		'.post-status.err { background: #fce8e8; color: #b30000; display: block; }',
    '.thread-indicator { font-size: 0.82rem; padding: 7px 10px; border-radius: 5px; margin-bottom: 10px; min-height: 28px; }',
    '.thread-indicator.checking { background: #f0f0f0; color: #666; }',
    '.thread-indicator.is-new { background: #e8f4e8; color: #1a6b1a; }',
    '.thread-indicator.is-comment { background: #e8f0fb; color: #1a3a7a; }',
    '.btn-force-new { margin-left: 10px; font-size: 0.78rem; padding: 2px 8px; border: 1px solid #aac; border-radius: 4px; background: #fff; cursor: pointer; color: #445; }',
		'.sync-error { background: #fff8e1; color: #7a5a00; border: 1px solid #ffe082; border-radius: 5px; padding: 6px 12px; font-size: 0.84rem; margin-bottom: 12px; }',
		'@media (max-width: 900px) { body { padding: 16px; } .admin-page-tabs { flex-wrap: nowrap; overflow-x: auto; padding-bottom: 6px; margin-right: -4px; } .admin-page-tab { flex: 0 0 auto; } .filter-bar { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); align-items: stretch; } .filter-bar label { display: flex; flex-direction: column; gap: 6px; } .filter-bar input, .filter-bar select { width: 100%; margin-left: 0; } .card-header, .fb-rank-head { flex-direction: column; align-items: flex-start; } .card-meta { white-space: normal; flex-wrap: wrap; gap: 6px 12px; } .details-grid { grid-template-columns: 1fr; } .detail-col:first-child { border-right: none; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 10px; } .forecast-period-card { grid-template-columns: 1fr; } .forecast-period-side { text-align: left; min-width: 0; } }',
		'@media (max-width: 640px) { body { padding: 12px; } h1 { font-size: 1.2rem; } .subtitle { font-size: 0.85rem; } .stats-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } .admin-panel, .token-exchange, .forecast-hub, .discussion-hub, .facebook-post-hub { padding: 16px; border-radius: 14px; } .filter-bar { grid-template-columns: 1fr; padding: 12px; } .filter-bar button { width: 100%; } .toggle-row { align-items: stretch; } .toggle-row select { width: 100%; min-width: 0; } .token-exchange button { width: 100%; margin-right: 0; } .forecast-hub-head, .facebook-post-head, .forecast-summary-head, .forecast-city-head, .modal-footer { flex-direction: column; align-items: stretch; } .forecast-refresh, .forecast-summary-actions button, .discussion-actions button, .discussion-actions a, .btn-preview { width: 100%; } .forecast-subtabs { display: grid; grid-template-columns: 1fr; } .forecast-loc-tab { width: 100%; min-width: 0; } .forecast-summary-actions, .discussion-actions { flex-direction: column; } .fb-rank-topline { align-items: flex-start; } .fb-rank-actions { display: flex; } .modal { width: 100%; max-width: none; height: 100dvh; max-height: none; border-radius: 0; } .modal-header, .modal-body, .modal-footer { padding: 14px; } .modal-body textarea { height: 50dvh; } }',
	].join('\n');
}
